### ISSUE TITLE
关于HTTPS链接不能下载的问题

### ISSUE THREAD

**Issue by BH4EHN** [HeiSir2014/M3U8-Downloader#24]
老版本 electron 里面的 node-fetch 证书过期了，需要将 electron 升级到 12.2.1 / 13.5.1 / 14.1.0 / 15.1.0 / 16 及以上版本；
这里提供一个基于 v2.0.6 版本的修复 [下载](https://github.com/BH4EHN/M3U8-Downloader/releases/tag/v2.0.6-fix-certificate-issue)

**Comment by HeiSir2014** [comment]
哇 感谢，我都没发现这个问题。
