### ISSUE TITLE
点击播放无反应

### ISSUE THREAD

**Issue by suliveevil** [HeiSir2014/M3U8-Downloader#29]
下载的是当前最新版v2.0.7

Model Name                    :  MacBook Air
Chipset Model                 :  Apple M1
System Version               :  macOS 12.3 (21E5222a)

能不能增加个调用外部播放器的功能啊？IINA 无需设置播放列表就能正常连续播放 TS 文件。

**Comment by llychao** [comment]
> 下载的是当前最新版v2.0.7
> 
> Model Name : MacBook Air Chipset Model : Apple M1 System Version : macOS 12.3 (21E5222a)
> 
> 能不能增加个调用外部播放器的功能啊？IINA 无需设置播放列表就能正常连续播放 TS 文件。

看看这个，三端直接运行，多线程，下载速度超出你的想象：https://github.com/llychao/m3u8-downloader
