### ISSUE TITLE
哈喽

### ISSUE THREAD

**Issue by Hunlongyu** [HeiSir2014/M3U8-Downloader#4]
你好， 
  看了你写的软件，很厉害。我之前也有想法写一个M3U8 downloader， 但是因为工作繁忙一直没有时间。今天偶然发现你写的软件，顿觉眼前一亮。
  我看了一下代码，逻辑清晰，功能强大。但是有一些瑕疵是目录结构不是很清晰。网上有很多 electron + vue 的开发脚手架。如：
```
1. https://github.com/SimulatedGREG/electron-vue
2. https://github.com/nklayman/vue-cli-plugin-electron-builder
```
我建议你可以尝试一下。我看你打包了 win，mac， 但是没有linux 的包。 其实这些可以使用 GitHub Actions  来实现全平台打包，并自动上传 release，以及实现软件自动更新。

如果可以的话， 我能参与你的这个项目么？

**Comment by HeiSir2014** [comment]
好呀，欢迎欢迎，我也是边学边写electron项目，还有一些需求我还是没有时间及时处理，main.js 也写的比较乱，加我QQ1586462详聊哈。
