### ISSUE TITLE
做了一个更加Mac风格的图标，希望不要嫌弃

### ISSUE THREAD

**Issue by zerobiubiu** [HeiSir2014/M3U8-Downloader#53]
<img width="512" alt="icon" src="https://user-images.githubusercontent.com/57526439/200109240-853cf09f-bd4b-484d-9ab5-a35aedb06e2a.png">

[icns下载地址](https://cdn.jsdelivr.net/gh/zerobiubiu/Figure-bed@main/uPic/icon.icns)

**Comment by HeiSir2014** [comment]
好的，怎么会嫌弃呢，谢谢啦，后续维护更新进去。
