### ISSUE TITLE
源码与发布不同？

### ISSUE THREAD

**Issue by yfdyh000** [HeiSir2014/M3U8-Downloader#56]
master，`yarn start`看到的界面与2.0.6和2.0.7不同，有“资源嗅探”和“我”板块。
https://github.com/HeiSir2014/M3U8-Downloader/tree/release-v2.0.7 怎么不在主干。

<s>而且，`yarn start`的版本，能正常下载某些多次重定向的m3u8 URL，已发布版本反而不行，会卡在初始化步骤。</s> 似乎是网络请求原因。

**Comment by HeiSir2014** [comment]
可以从2.0.7 拉一个分支，在那个分支继续开发发版，master分支作为一个新版本后续开发。
