### ISSUE TITLE
Malware encoded

### ISSUE THREAD

**Issue by igronus** [HeiSir2014/M3U8-Downloader#72]
![Screenshot 2023-02-15 at 15 16 59](https://user-images.githubusercontent.com/4248701/219038154-38285296-2e19-4d27-ac79-22356a4d4d17.png)

**Comment by SAOJSM** [comment]
If you use it in China, it may be that the broadband provider hijacked your network, and there is no problem at all when using it abroad

**Comment by igronus** [comment]
Nope, I am not in China.

**Comment by SAOJSM** [comment]
Could you provide your user environment ?
Also please provide the website and m3u8 link you use for test.

**Comment by HeiSir2014** [comment]
please use "release-v2.0.7" branch.  https://github.com/HeiSir2014/M3U8-Downloader/tree/release-v2.0.7
