### ISSUE TITLE
建议处理 M3U8 中指向另一 M3U8 的情况

### ISSUE THREAD

**Issue by candy76041820** [HeiSir2014/M3U8-Downloader#9]
直接从页面上嗅探到的 A.m3u8 中内容是指向另一 B.m3u8 的地址，建议在这种情况下递归解析直到列表中不是仅有一个 m3u8、且递归层数未超过某限制值（可由用户指定）的情况。

**Comment by HeiSir2014** [comment]
对的，有些视频源包含多码率清晰度的视频，目前程序还做到支持，接下来更新会解决这个问题。

**Comment by HeiSir2014** [comment]
使用新版本2.0.5+ 可以解决这个问题。

**Comment by candy76041820** [comment]
别忘了更新下载链接哦。
